#!/usr/bin/env bash
# Apply Honco's Jitsi customisations to a docker-jitsi-meet checkout.
#
# The upstream checkout lives outside this repo (it is vendor code, like the
# Mattermost tree), so the customisations that make it a *Honco* deployment
# were previously only in one person's home directory. Losing them is silent:
# recording keeps working right up until the next rebuild, then fails in ways
# that look like Jitsi bugs. This script is the reproducible form of them.
#
#   ./apply-honco-meet-config.sh [/path/to/docker-jitsi-meet]
#
# Idempotent: re-running changes nothing. It never writes secrets -- the
# passwords in .env are generated by upstream's own gen-passwords.sh and are
# not this script's business.
set -euo pipefail

MEET_DIR="${1:-$HOME/honco-meet}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OVERRIDE="$MEET_DIR/docker-compose.override.yml"

[ -d "$MEET_DIR" ] || { echo "no docker-jitsi-meet checkout at $MEET_DIR" >&2; exit 1; }
[ -f "$MEET_DIR/docker-compose.yml" ] || { echo "$MEET_DIR is not a docker-jitsi-meet checkout" >&2; exit 1; }

say() { printf '  %s\n' "$*"; }

# The LAN address peers must reach. Derived, never hardcoded: a literal here
# goes stale the moment the machine changes network, and the failure mode is
# a call that connects and then has no media.
LAN_IP="${HONCO_LAN_IP:-$("$HERE/lan-address.sh")}"
say "LAN address: $LAN_IP"

echo "== docker-compose.override.yml =="
if [ ! -f "$OVERRIDE" ]; then
    printf 'services:\n' > "$OVERRIDE"
    say "created $OVERRIDE"
fi

# Each block is added only if its marker is absent, so this can be re-run
# over a file that already has some of them.
add_block() {
    local marker="$1" block="$2"
    if grep -q "$marker" "$OVERRIDE"; then
        say "already present: $marker"
    else
        printf '%s\n' "$block" >> "$OVERRIDE"
        say "added: $marker"
    fi
}

add_block "honco-backgrounds" "$(cat <<'YAML'

  web:
    volumes:
      - ${CONFIG}/web-backgrounds:/usr/share/jitsi-meet/images/honco-backgrounds:ro
YAML
)"

add_block "JIBRI_HTTP_API_EXTERNAL_PORT" "$(cat <<'YAML'

  jibri:
    ports:
      # Jibri's control API, loopback only. Honco's recording service runs
      # natively on this host, not in the meet.jitsi network, so it needs a
      # way in -- but nothing off-box may drive recordings.
      - '127.0.0.1:${JIBRI_HTTP_API_EXTERNAL_PORT:-2222}:2222'
    volumes:
      # The base jibri.yml mounts only /config, so a finished recording had
      # nowhere persistent to land. This is where finalize.sh finds it.
      - ${CONFIG}/storage/jibri:/storage:Z
    environment:
      # Jibri drives a real Chrome INSIDE this container, so `localhost` here
      # is the Jibri container itself. The host-facing PUBLIC_URL is
      # unreachable from it and Chrome fails with ERR_CONNECTION_REFUSED
      # before ever joining -- reported as FailedToJoinCall, with no media
      # recorded and finalize never running. PUBLIC_URL is the only input the
      # image's xmpp.conf template accepts for base-url, so scope it to this
      # one service and let it reach the web container by service name.
      - PUBLIC_URL=https://web
YAML
)"

add_block "XMPP_MUC_MODULES" "$(cat <<'YAML'

  prosody:
    environment:
      # Jitsi's own mod_muc_size: the only supported way this version answers
      # "who is in this room". There is no event/push module in stable-9955.
      - XMPP_MUC_MODULES=muc_size
    ports:
      # Loopback only, like jicofo's 8888 and jibri's 2222. Room occupancy
      # must never be queryable from off the host.
      - '127.0.0.1:${PROSODY_HTTP_EXTERNAL_PORT:-5280}:5280'
YAML
)"

echo
echo "== .env =="
ENV_FILE="$MEET_DIR/.env"
if [ -f "$ENV_FILE" ]; then
    if grep -qE '^JVB_ADVERTISE_IPS=' "$ENV_FILE"; then
        say "JVB_ADVERTISE_IPS already set in .env (leaving it alone)"
    else
        say "JVB_ADVERTISE_IPS is not in .env -- meet.sh exports it at startup"
        say "from lan-address.sh, which is preferred: a value written here"
        say "goes stale when the machine changes network."
    fi
else
    say "no .env yet -- run upstream's gen-passwords.sh first"
fi

echo
echo "== validate =="
cd "$MEET_DIR"
docker compose -f docker-compose.yml -f jibri.yml -f docker-compose.override.yml config --quiet \
    && say "compose config is valid"

echo
echo "Apply with:  $MEET_DIR/meet.sh up"
echo
echo "NOTE: recreating prosody drops jibri's brewery registration and jicofo"
echo "does not re-detect it on its own. After a prosody recreate, restart"
echo "jibri and jicofo or recordings fail with 'Unable to find an available"
echo "Jibri':"
echo "    $MEET_DIR/meet.sh restart jibri"
echo "    $MEET_DIR/meet.sh restart jicofo"
